import { v4 as uuidv4 } from "uuid"
function ChillHop() {
    return [
        {
            name: "Taisou Zamurai Ending",
            cover: "./assets/covers/KaerMorhen.jpg",
            artist: "MAPPA",
            audio: "./assets/songs/Taisou Zamurai ED.mp3",
            color: ["#205950","#2ab3bf"],
            id: uuidv4(),
            active: true,
        },
        {
            name: "Taisou Zamurai ED Piano",
            cover: "./assets/covers/KaerMorhen.jpg",
            artist: "MAPPA",
            audio: "./assets/songs/Taisou Zamurai ED Piano.mp3",
            color: ["#EF8EA9","#ab417f"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Berserkir (Ezio's Family)",
            cover: "./assets/covers/NoMansLand.jpg",
            artist: "Jesper Kyd",
            audio: "./assets/songs/Berserkir (Ezio's Family).mp3",
            color: ["#CD607D","#c94043"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Kaer Morhen",
            cover: "./assets/covers/KaerMorhen.jpg",
            artist: "CDProjectRed",
            audio: "./assets/songs/Kaer Morhen - Witcher 3.mp3",
            color: ["#EF8EA9","#ab417f"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Track Meet",
            cover: "./assets/covers/NoMansLand.jpg",
            artist: "Yuki Hayashi",
            audio: "./assets/songs/Track Meet - Yuki Hayashi.mp3",
            color: ["#CD607D","#c94043"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Lost in Paradise",
            cover: "./assets/covers/Mountain.jpg",
            artist: "Aklo",
            audio: "./assets/songs/LOST IN PARADISE feat. AKLO.mp3",
            color: ["#205950","#2ab3bf"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Viking War Chant!",
            cover: "./assets/covers/NoMansLand.jpg",
            artist: "Einar Selvik",
            audio: "./assets/songs/Nordic War Chant!.mp3",
            color: ["#205950","#2ab3bf"],
            id: uuidv4(),
            active: false,
        },
        {
            name: "Life Flows like a Conveyor Belt",
            cover: "./assets/covers/Nature.jpg",
            artist: "Gintama",
            audio: "./assets/songs/Life Flows Like a Conveyor Belt.mp3",
            color: ["#CD607D","#c94043"],
            id: uuidv4(),
            active: false,
        },
    ]
}